---
- name: install ubuntu package requirements
  package: name={{ item }} state=latest update_cache=yes
  with_items:
    - python-pip
    - python-virtualenv
  tags: [skip_ansible_lint]

- name: virtualenv - install setuptools
  pip:
    name: setuptools==44.0.0
    virtualenv: /opt/ictf/venv/gamebot
  become: true

- name: virtualenv - install requirements
  pip:
    requirements=/opt/ictf/gamebot/requirements.txt
    virtualenv=/opt/ictf/venv/gamebot

- include_role:
    name: register_service_daemon
  vars:
    service_name: ictf-gamebot
    description: "Setup Gamebot service daemon"
    command: "/opt/ictf/venv/gamebot/bin/python gamebot.py"
    working_directory: "/opt/ictf/gamebot"

- include_role:
    name: common_server
  vars:
    server_hostname: GameBOT

- include_role:
    name: deploy_prometheus_node_exporter