- hosts: localhost
  remote_user: root
  become: true

  vars:

    ICTF_TI_SERVER_URL: "https://api.seba.net"
    ICTF_TI_SECRET_KEY: "{{ lookup('password','/opt/ictf/secrets/ti_secret length=25') }}"

    SENDGRID_API_KEY: ""
    ICTF_EMAIL_SENDER: ""
    ICTF_TI_SERVER_DOMAIN: "api.ictf2017.net"

    # to obtain a SSL cert with letsencrypt see https://certbot.eff.org/#ubuntutrusty-nginx
    SSL_CERTIFICATE_PATH: "/etc/letsencrypt/live/api.ictf2017.net/fullchain.pem"
    SSL_CERTIFICATE_KEY_PATH: "/etc/letsencrypt/live/api.ictf2017.net/privkey.pem"
    ENABLE_SSL: "0"

    # Team interface config
    REGISTRATION_OPEN: "False"
    GAME_STARTED: "False"
    SUBMISSION_OPEN: "False"
    
  handlers:
  - name: restart ictf-teaminterface
    service: name=ictf-teaminterface state=restarted

  - name: reload nginx
    service: name=nginx state=reloaded

  tasks:

  - name: setting hostname
    hostname:
      name: "teaminterface"

  - name: Add mappings to /etc/hosts
    blockinfile:
      dest: /etc/hosts
      block: |
        {{ item.ip }} {{ item.name }}
      marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
    with_items:
      - { name: "teaminterface", ip: 127.0.0.1 }

  - name: teaminterface - write config.py
    template:
      src="/opt/ictf/teaminterface/config.py.example"
      dest="/opt/ictf/teaminterface/config.py"
      mode="0666"
    notify:
      - restart ictf-teaminterface
      - reload nginx
