---
- hosts: all

  roles:
    - teamvm_primed

  vars:
    game_config: "{{ lookup('file', '{{ICTF_FRAMEWORK_DIR_HOST}}/game_config.json') | from_json }}"
    services: "{{ game_config | json_query('services[?state==`enabled`].name') }}"
    team_names: "{{ game_config | json_query('teams[].name') }}"

    host_services_path: "{{ game_config.service_metadata.host_dir }}"
    guest_services_path: "{{ game_config.service_metadata.guest_dir }}"
