- name: install pip
  apt:
    name: python-pip

- name: install pip3
  apt:
    name: python3-pip

- name: install docker
  apt:
    name: docker.io

- name: install docker-compose
  apt:
    name: docker-compose

- name: install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.23.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: add user to docker group
  command: usermod -aG docker "{{ICTF_USER}}"
